"use client";

import { useEffect, useMemo, useRef } from "react";
import { useAuth } from "@/lib/auth-context";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, X } from "lucide-react";
import type { AiInsight } from "@minea/types";
import { aiApi } from "@/lib/api-client";
import { useTenancy } from "@/lib/tenancy";
import { useAuthQueryEnabled } from "@/lib/use-auth-query-enabled";
import { cn } from "@/lib/utils";

function formatAnalysedAgo(iso: string | null): string {
  if (!iso) return "not yet analysed";
  const diffMin = Math.floor((Date.now() - new Date(iso).getTime()) / 60_000);
  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin} min ago`;
  return `${Math.floor(diffMin / 60)}h ago`;
}

function severityStyle(severity: AiInsight["severity"]) {
  switch (severity) {
    case "high":
      return { dot: "bg-red-500", badge: "text-red-700 bg-red-50 border-red-100" };
    case "medium":
      return { dot: "bg-amber-500", badge: "text-amber-800 bg-amber-50 border-amber-100" };
    default:
      return { dot: "bg-blue-400", badge: "text-blue-700 bg-blue-50 border-blue-100" };
  }
}

function InsightItem({ insight }: { insight: AiInsight }) {
  const style = severityStyle(insight.severity);
  const examples = insight.examples ?? [];
  const note = insight.impact_note || insight.description;

  return (
    <div className="px-5 py-4 border-b border-gray-100 hover:bg-stone-50/60 transition-colors">
      <div className="flex items-start gap-3">
        <span className={cn("h-2 w-2 rounded-full mt-1.5 flex-shrink-0", style.dot)} />
        <div className="min-w-0 flex-1">
          <p className="text-sm font-semibold text-gray-900 leading-snug">{insight.title}</p>
          {examples.length > 0 && (
            <p className="text-xs text-gray-500 mt-1">{examples.join(" · ")}</p>
          )}
          {note && <p className="text-xs text-gray-400 mt-1.5 leading-relaxed">{note}</p>}
        </div>
      </div>
    </div>
  );
}

interface Props {
  open: boolean;
  onClose: () => void;
}

export function ArchitectureInsightsPanel({ open, onClose }: Props) {
  const { getToken } = useAuth();
  const { orgSlug, workspaceSlug } = useTenancy();
  const queryClient = useQueryClient();
  const enabled = useAuthQueryEnabled(orgSlug, workspaceSlug);
  const panelRef = useRef<HTMLDivElement>(null);
  const autoGeneratedRef = useRef(false);

  const queryKey = ["ai-insights", orgSlug, workspaceSlug] as const;

  const { data, isLoading } = useQuery({
    queryKey,
    queryFn: async () => {
      const token = await getToken();
      return aiApi.listInsights(orgSlug, workspaceSlug, token!);
    },
    enabled: enabled && open,
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const token = await getToken();
      await aiApi.generateInsights(orgSlug, workspaceSlug, token!);
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey }),
  });

  const insights = data?.insights ?? [];

  useEffect(() => {
    if (!open) {
      autoGeneratedRef.current = false;
      return;
    }
    if (
      enabled &&
      data &&
      (data.count ?? insights.length) === 0 &&
      !autoGeneratedRef.current &&
      !generateMutation.isPending
    ) {
      autoGeneratedRef.current = true;
      generateMutation.mutate();
    }
  }, [open, enabled, data, insights.length, generateMutation.isPending, generateMutation]);

  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    if (open) document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [open, onClose]);

  const { criticalCount, warningCount } = useMemo(() => {
    return {
      criticalCount: insights.filter((i) => i.severity === "high").length,
      warningCount: insights.filter((i) => i.severity === "medium").length,
    };
  }, [insights]);

  if (!open) return null;

  return (
    <>
      <div className="fixed inset-0 z-[200] bg-black/20" onClick={onClose} />
      <div
        ref={panelRef}
        className="fixed right-0 top-0 h-full w-full max-w-[400px] bg-white shadow-2xl z-[210] flex flex-col"
      >
        <div className="px-5 py-4 border-b border-gray-200 flex items-start justify-between gap-3 flex-shrink-0">
          <div>
            <h2 className="text-base font-semibold text-gray-900">Architecture insights</h2>
            <p className="text-xs text-gray-500 mt-0.5">
              {data?.count ?? 0} gap{(data?.count ?? 0) === 1 ? "" : "s"} detected · analysed{" "}
              {formatAnalysedAgo(data?.analysed_at ?? null)}
            </p>
          </div>
          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              type="button"
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
              title="Re-analyse"
              className="p-1.5 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors disabled:opacity-50"
            >
              <RefreshCw size={15} className={generateMutation.isPending ? "animate-spin" : ""} />
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors"
            >
              <X size={16} />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto">
          {isLoading || generateMutation.isPending ? (
            <p className="px-5 py-8 text-sm text-gray-400">Analysing architecture…</p>
          ) : insights.length === 0 ? (
            <div className="px-5 py-8 text-center">
              <p className="text-sm text-gray-500 mb-1">No gaps detected</p>
              <p className="text-xs text-gray-400">Your architecture model looks complete.</p>
            </div>
          ) : (
            insights.map((insight) => <InsightItem key={insight.id} insight={insight} />)
          )}
        </div>

        {(criticalCount > 0 || warningCount > 0) && (
          <div className="px-5 py-3 border-t border-gray-100 flex items-center gap-3 text-[11px] text-gray-500 flex-shrink-0">
            {criticalCount > 0 && (
              <span className="inline-flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full bg-red-500" />
                {criticalCount} critical
              </span>
            )}
            {warningCount > 0 && (
              <span className="inline-flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full bg-amber-500" />
                {warningCount} warning{warningCount === 1 ? "" : "s"}
              </span>
            )}
          </div>
        )}
      </div>
    </>
  );
}

/** Badge count for the nav bell — high + medium severity insights. */
export function useInsightsBadgeCount(orgSlug: string, workspaceSlug: string) {
  const { getToken } = useAuth();
  const enabled = useAuthQueryEnabled(orgSlug, workspaceSlug);

  const { data } = useQuery({
    queryKey: ["ai-insights", orgSlug, workspaceSlug],
    queryFn: async () => {
      const token = await getToken();
      return aiApi.listInsights(orgSlug, workspaceSlug, token!);
    },
    enabled,
    staleTime: 5 * 60_000,
  });

  const count = useMemo(() => {
    const items = data?.insights ?? [];
    return items.filter((i) => i.severity === "high" || i.severity === "medium").length;
  }, [data?.insights]);

  const criticalOnly = useMemo(() => {
    const items = data?.insights ?? [];
    return items.some((i) => i.severity === "high");
  }, [data?.insights]);

  return { count, criticalOnly, total: data?.count ?? 0 };
}
