/** Same list as tools.json. The unit runner cannot import JSON, so the app reads this module. */
export const TOOL_CATALOG = [
  { name: "Salesforce", aliases: ["salesforce", "sfdc"], vendor: "Salesforce", category: "CRM", hosting: "saas", kind: "app", typicalAnnual: 18000, unit: "year", ssoUsual: true },
  { name: "QuickBooks Online", aliases: ["quickbooks", "quickbooks online", "qbo"], vendor: "Intuit", category: "Finance", hosting: "saas", kind: "app", typicalAnnual: 900, unit: "year" },
  { name: "Microsoft 365", aliases: ["microsoft 365", "m365", "office 365"], vendor: "Microsoft", category: "Productivity", hosting: "saas", kind: "app", typicalAnnual: 15000, unit: "year", idp: true },
  { name: "Shopify", aliases: ["shopify"], vendor: "Shopify", category: "Commerce", hosting: "saas", kind: "app", typicalAnnual: 348, unit: "year" },
  { name: "AS400", aliases: ["as400", "as/400", "ibm i"], vendor: "IBM", category: "Server", hosting: "own", kind: "server", typicalAnnual: null, unit: "year" },
  { name: "SPS Commerce", aliases: ["sps commerce", "edi"], vendor: "SPS Commerce", category: "Integration", hosting: "either", kind: "app", typicalAnnual: null, unit: "year" },
  { name: "TrueCommerce", aliases: ["truecommerce", "edi"], vendor: "TrueCommerce", category: "Integration", hosting: "either", kind: "app", typicalAnnual: null, unit: "year" },
  { name: "Cleo", aliases: ["cleo", "cleo integration cloud", "edi"], vendor: "Cleo", category: "Integration", hosting: "either", kind: "app", typicalAnnual: null, unit: "year" },
  { name: "BarTender", aliases: ["bartender", "bar tender"], vendor: "Seagull", category: "Operations", hosting: "either", kind: "app", typicalAnnual: 1200, unit: "year", hints: ["label", "printing", "barcode"] },
  { name: "Zoom Workplace", aliases: ["zoom", "zoom workplace"], vendor: "Zoom", category: "Meetings", hosting: "saas", kind: "app", typicalAnnual: 1800, unit: "year", ssoUsual: true },
  { name: "Oracle NetSuite", aliases: ["netsuite", "oracle netsuite"], vendor: "Oracle", category: "Finance", hosting: "saas", kind: "app", typicalAnnual: 12000, unit: "year", ssoUsual: true },
  { name: "Slack", aliases: ["slack"], vendor: "Salesforce", category: "Productivity", hosting: "saas", kind: "app", typicalAnnual: 900, unit: "year", ssoUsual: true },
  { name: "Dropbox", aliases: ["dropbox"], vendor: "Dropbox", category: "Files", hosting: "saas", kind: "app", typicalAnnual: 720, unit: "year", ssoUsual: true },
  { name: "HubSpot", aliases: ["hubspot"], vendor: "HubSpot", category: "Marketing", hosting: "saas", kind: "app", typicalAnnual: 10800, unit: "year", ssoUsual: true },
  { name: "Snowflake", aliases: ["snowflake"], vendor: "Snowflake", category: "Analytics", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year", ssoUsual: true },
  { name: "Databricks", aliases: ["databricks"], vendor: "Databricks", category: "Analytics", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year", ssoUsual: true },
  { name: "Microsoft Fabric", aliases: ["microsoft fabric", "fabric"], vendor: "Microsoft", category: "Analytics", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Azure Functions", aliases: ["azure functions"], vendor: "Microsoft", category: "Infrastructure", hosting: "paas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "AWS Lambda", aliases: ["aws lambda", "lambda"], vendor: "Amazon", category: "Infrastructure", hosting: "paas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Azure AI Foundry", aliases: ["azure ai foundry"], vendor: "Microsoft", category: "AI", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Copilot Studio", aliases: ["copilot studio"], vendor: "Microsoft", category: "AI", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Bedrock", aliases: ["bedrock", "amazon bedrock"], vendor: "Amazon", category: "AI", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Vertex AI", aliases: ["vertex ai", "vertex"], vendor: "Google", category: "AI", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year" },
  { name: "Google Workspace", aliases: ["google workspace", "g suite", "gsuite", "gmail"], vendor: "Google", category: "Productivity", hosting: "saas", kind: "app", typicalAnnual: null, unit: "year", idp: true },
  { name: "Okta", aliases: ["okta"], vendor: "Okta", category: "Identity", hosting: "saas", kind: "app", typicalAnnual: null, unit: "year", idp: true },
  { name: "Microsoft Entra ID", aliases: ["entra", "entra id", "microsoft entra", "azure ad", "azure active directory"], vendor: "Microsoft", category: "Identity", hosting: "saas", kind: "platform", typicalAnnual: null, unit: "year", idp: true },
];
