// Mirror of the backend ALLOWED_TRIPLES — used for frontend validation
export const ALLOWED_TRIPLES_FRONTEND: [string, string, string][] = [
  ["depends_on", "capability", "capability"],
  ["part_of", "application", "application"],
  ["part_of", "application", "solution"],
  ["calls", "application", "application"],
  ["uses", "application", "technical_capability"],
  ["contains", "data_store", "data_object"],
  ["connects", "integration_flow", "api"],
  ["connects", "integration_flow", "event"],
  ["routes", "message_broker", "event"],
  ["supported_by", "capability", "application"],
  ["supported_by", "capability", "solution"],
  ["supported_by", "capability", "technical_capability"],
  ["exposes", "application", "api"],
  ["publishes", "application", "event"],
  ["consumes", "application", "api"],
  ["subscribes", "application", "event"],
  ["stores_in", "application", "data_store"],
  ["exposes", "application", "tool"],
  ["runs_on", "application", "cloud_service"],
  ["runs_on", "data_store", "cloud_service"],
  ["runs_on", "message_broker", "cloud_service"],
  ["affects", "initiative", "capability"],
  ["affects", "initiative", "application"],
  ["replaces", "application", "application"],
  ["uses_model", "agent", "model"],
  ["can_call", "agent", "tool"],
  ["supports", "agent", "capability"],
  ["escalates_to", "agent", "application"],
  ["accesses", "tool", "data_object"],
  ["connects_to", "tool", "application"],
];
