// Mirror of the backend ALLOWED_TRIPLES — used for frontend validation
export const ALLOWED_TRIPLES_FRONTEND: [string, string, string][] = [
  ["depends_on", "capability", "capability"],
  ["part_of", "application", "application"],
  ["part_of", "application", "solution"],
  ["calls", "application", "application"],
  ["uses", "application", "technical_capability"],
  ["contains", "data_store", "data_object"],
  ["connects", "integration_flow", "api"],
  ["connects", "integration_flow", "event"],
  ["routes", "message_broker", "event"],
  ["routes", "tool", "event"],
  ["hosts", "tool", "api"],
  ["carries", "tool", "integration_flow"],
  ["supported_by", "capability", "application"],
  ["supported_by", "capability", "solution"],
  ["supported_by", "capability", "technical_capability"],
  ["exposes", "application", "api"],
  ["exposes", "component", "api"],
  ["publishes", "application", "event"],
  ["publishes", "component", "event"],
  ["publishes", "data_object", "event"],
  ["consumes", "application", "api"],
  ["subscribes", "application", "event"],
  ["subscribes", "component", "event"],
  ["reads", "application", "data_store"],
  ["writes", "application", "data_store"],
  ["owns", "application", "data_store"],
  ["creates", "application", "data_object"],
  ["updates", "application", "data_object"],
  ["reads", "application", "data_object"],
  ["owns", "application", "data_object"],
  ["belongs_to", "data_object", "data_domain"],
  ["belongs_to", "data_store", "data_domain"],
  ["belongs_to", "application", "data_domain"],
  ["exposes", "application", "tool"],
  ["part_of", "component", "application"],
  ["runs_on", "component", "tool"],
  ["runs_on", "component", "model"],
  ["runs_on", "component", "cloud_service"],
  ["built_on", "component", "cloud_service"],
  ["runs_on", "application", "cloud_service"],
  ["runs_on", "solution", "cloud_service"],
  ["runs_on", "technical_capability", "cloud_service"],
  ["runs_on", "application", "model"],
  ["runs_on", "solution", "model"],
  ["runs_on", "technical_capability", "model"],
  ["runs_on", "data_store", "cloud_service"],
  ["runs_on", "message_broker", "cloud_service"],
  ["affects", "initiative", "capability"],
  ["affects", "initiative", "application"],
  ["affects", "tech_debt", "application"],
  ["affects", "tech_debt", "solution"],
  ["affects", "tech_debt", "technical_capability"],
  ["affects", "tech_debt", "component"],
  ["affects", "tech_debt", "api"],
  ["affects", "tech_debt", "event"],
  ["affects", "tech_debt", "integration_flow"],
  ["affects", "tech_debt", "tool"],
  ["affects", "tech_debt", "data_object"],
  ["affects", "tech_debt", "data_store"],
  ["affects", "tech_debt", "data_domain"],
  ["affects", "tech_debt", "cloud_service"],
  ["affects", "tech_debt", "model"],
  ["resolves", "roadmap_item", "tech_debt"],
  ["replaces", "application", "application"],
  ["uses_model", "agent", "model"],
  ["can_call", "agent", "tool"],
  ["supports", "agent", "capability"],
  ["escalates_to", "agent", "application"],
  ["accesses", "tool", "data_object"],
  ["connects_to", "tool", "application"],
];

/** Canonical direction only — do not offer inverse in the relationship picker. */
export const OUTBOUND_ONLY_TRIPLES = new Set(["belongs_to:application:data_domain"]);

export function tripleKey(type: string, from: string, to: string): string {
  return `${type}:${from}:${to}`;
}
